#include "VulkanVertexLayout.h"

namespace vkc
{
    DEFINE_VERTEX_ATTRIBUTE_TYPE(glm::ivec4, VK_FORMAT_R32G32B32A32_SINT)
    DEFINE_VERTEX_ATTRIBUTE_TYPE(glm::ivec3, VK_FORMAT_R32G32B32_SINT)
    DEFINE_VERTEX_ATTRIBUTE_TYPE(glm::ivec2, VK_FORMAT_R32G32_SINT)
    DEFINE_VERTEX_ATTRIBUTE_TYPE(int32_t, VK_FORMAT_R32_SINT)

    DEFINE_VERTEX_ATTRIBUTE_TYPE(glm::uvec4, VK_FORMAT_R32G32B32A32_UINT)
    DEFINE_VERTEX_ATTRIBUTE_TYPE(glm::uvec3, VK_FORMAT_R32G32B32_UINT)
    DEFINE_VERTEX_ATTRIBUTE_TYPE(glm::uvec2, VK_FORMAT_R32G32_UINT)
    DEFINE_VERTEX_ATTRIBUTE_TYPE(uint32_t, VK_FORMAT_R32_UINT)

    DEFINE_VERTEX_ATTRIBUTE_TYPE(glm::vec4, VK_FORMAT_R32G32B32A32_SFLOAT)
    DEFINE_VERTEX_ATTRIBUTE_TYPE(glm::vec3, VK_FORMAT_R32G32B32_SFLOAT)
    DEFINE_VERTEX_ATTRIBUTE_TYPE(glm::vec2, VK_FORMAT_R32G32_SFLOAT)
    DEFINE_VERTEX_ATTRIBUTE_TYPE(float, VK_FORMAT_R32_SFLOAT)

    DEFINE_VERTEX_ATTRIBUTE_TYPE(glm::dvec4, VK_FORMAT_R64G64B64A64_SFLOAT)
    DEFINE_VERTEX_ATTRIBUTE_TYPE(glm::dvec3, VK_FORMAT_R64G64B64_SFLOAT)
    DEFINE_VERTEX_ATTRIBUTE_TYPE(glm::dvec2, VK_FORMAT_R64G64_SFLOAT)
    DEFINE_VERTEX_ATTRIBUTE_TYPE(double, VK_FORMAT_R64_SFLOAT)
}